class Config:
    PRINT_TETRIS_INFO = True
    PRINT_DEBUG_TETRIS_INFO = False

    PRINT_SOLVER_INFO = True
    PRINT_BOARD = True

    PRINT_DEEP_SOLVER_INFO = True

    CHECK_SEQ_SCORE = True

    # PRINT_TETRIS_INFO = False
    # PRINT_SOLVER_INFO = False


    DEEPSOLVER_DEPTH = 1
    DEEPSOLVER_COEF_GRAVITY = 50.0
    DEEPSOLVER_COEF_HOLE1 = 1.0
    DEEPSOLVER_COEF_HOLE2 = 1.0
    DEEPSOLVER_COEF_HOLE3 = 1.0
    DEEPSOLVER_COEF_UNF_ROW = 0.5
    DEEPSOLVER_COEF_SMOOTH = 2.0
    MAGIC_BUFFER = 0

    VERIFY_NP_VALID = False
